/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Iuri
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jmnList = new javax.swing.JMenu();
        jmiPais = new javax.swing.JMenuItem();
        jmiEstado = new javax.swing.JMenuItem();
        jmiCidade = new javax.swing.JMenuItem();
        jmiEndereco = new javax.swing.JMenuItem();
        jmiPessoa = new javax.swing.JMenuItem();
        jmiCliente = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        Produto = new javax.swing.JMenuItem();
        jmiTipo = new javax.swing.JMenuItem();
        jmiVenda = new javax.swing.JMenuItem();
        jmiVendaProduto = new javax.swing.JMenuItem();
        jmiParcela = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo de Software");
        setLocationByPlatform(true);
        setResizable(false);

        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jmnList.setMnemonic('e');
        jmnList.setText("Cadastrar");
        jmnList.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jmiPais.setText("País");
        jmiPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPaisActionPerformed(evt);
            }
        });
        jmnList.add(jmiPais);

        jmiEstado.setText("Estado");
        jmiEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEstadoActionPerformed(evt);
            }
        });
        jmnList.add(jmiEstado);

        jmiCidade.setText("Cidade");
        jmiCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCidadeActionPerformed(evt);
            }
        });
        jmnList.add(jmiCidade);

        jmiEndereco.setText("Endereço");
        jmiEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEnderecoActionPerformed(evt);
            }
        });
        jmnList.add(jmiEndereco);

        jmiPessoa.setText("Pessoa");
        jmiPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPessoaActionPerformed(evt);
            }
        });
        jmnList.add(jmiPessoa);

        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jmnList.add(jmiCliente);

        jmiFornecedor.setText("Fornecedor");
        jmiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedorActionPerformed(evt);
            }
        });
        jmnList.add(jmiFornecedor);

        Produto.setText("Produto");
        Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoActionPerformed(evt);
            }
        });
        jmnList.add(Produto);

        jmiTipo.setText("Tipo");
        jmiTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTipoActionPerformed(evt);
            }
        });
        jmnList.add(jmiTipo);

        jmiVenda.setText("Venda");
        jmiVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVendaActionPerformed(evt);
            }
        });
        jmnList.add(jmiVenda);

        jmiVendaProduto.setText("VendaProduto");
        jmiVendaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVendaProdutoActionPerformed(evt);
            }
        });
        jmnList.add(jmiVendaProduto);

        jmiParcela.setText("Parcela");
        jmiParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiParcelaActionPerformed(evt);
            }
        });
        jmnList.add(jmiParcela);

        menuBar.add(jmnList);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPaisActionPerformed
        PaisView dialog = new PaisView(this, true); //alterar
        dialog.setVisible(true); //alterar
    }//GEN-LAST:event_jmiPaisActionPerformed

    private void jmiEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEstadoActionPerformed
        EstadoView dialog = new EstadoView(this, true);
        dialog.setVisible(true); 
    }//GEN-LAST:event_jmiEstadoActionPerformed

    private void jmiPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPessoaActionPerformed
        PessoaView dialog = new PessoaView(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiPessoaActionPerformed

    private void jmiCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCidadeActionPerformed
        CidadeView dialog = new CidadeView(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiCidadeActionPerformed

    private void jmiEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEnderecoActionPerformed
        EnderecoView dialog = new EnderecoView(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiEnderecoActionPerformed

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        ClienteView dialog = new ClienteView(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedorActionPerformed
        FornecedorView dialog = new FornecedorView(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiFornecedorActionPerformed

    private void ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoActionPerformed
        ProdutoView dialog = new ProdutoView(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_ProdutoActionPerformed

    private void jmiTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTipoActionPerformed
        TipoView dialog = new TipoView(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiTipoActionPerformed

    private void jmiVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVendaActionPerformed
        VendaView dialog = new VendaView(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiVendaActionPerformed

    private void jmiVendaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVendaProdutoActionPerformed
        VendaProdutoView dialog = new VendaProdutoView(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiVendaProdutoActionPerformed

    private void jmiParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiParcelaActionPerformed
        ParcelaView dialog = new ParcelaView(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiParcelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Produto;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem jmiCidade;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiEndereco;
    private javax.swing.JMenuItem jmiEstado;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiPais;
    private javax.swing.JMenuItem jmiParcela;
    private javax.swing.JMenuItem jmiPessoa;
    private javax.swing.JMenuItem jmiTipo;
    private javax.swing.JMenuItem jmiVenda;
    private javax.swing.JMenuItem jmiVendaProduto;
    private javax.swing.JMenu jmnList;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
